//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yorot_Avalonia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yorot_Avalonia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addon_settings {
            get {
                object obj = ResourceManager.GetObject("addon_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon avalonia_logo {
            get {
                object obj = ResourceManager.GetObject("avalonia_logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back_b {
            get {
                object obj = ResourceManager.GetObject("back_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back_w {
            get {
                object obj = ResourceManager.GetObject("back_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calc {
            get {
                object obj = ResourceManager.GetObject("calc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar {
            get {
                object obj = ResourceManager.GetObject("calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;title&gt;Yorot&lt;/title&gt;
        ///    &lt;style&gt;
        ///        html,
        ///        body {
        ///            height: 100%;
        ///            background: #660000;
        ///            color: white;
        ///            font: Ubuntu;
        ///        }
        ///
        ///        .parent {
        ///            height: 200px;
        ///            background: #660000;
        ///            display: flex;
        ///            align-items: center;
        ///            justify-content: center;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body class=&quot;parent&quot;&gt;
        ///    &lt;div class=&quot;content&quot;&gt;
        ///        &lt;h1 style=&quot;text-align: center&quot;&gt;[W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string certerror {
            get {
                return ResourceManager.GetString("certerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_w {
            get {
                object obj = ResourceManager.GetObject("close_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CloseHover {
            get {
                object obj = ResourceManager.GetObject("CloseHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap colman {
            get {
                object obj = ResourceManager.GetObject("colman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap console {
            get {
                object obj = ResourceManager.GetObject("console", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customization {
            get {
                object obj = ResourceManager.GetObject("customization", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap default_pofile_pic {
            get {
                object obj = ResourceManager.GetObject("default_pofile_pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap downloads {
            get {
                object obj = ResourceManager.GetObject("downloads", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;root&gt;
        ///	&lt;Group Name=&quot;#YOROT-ROOT&quot;&gt;
        ///		&lt;Name&gt;English (United Kingdom)&lt;/Name&gt;
        ///		&lt;Author&gt;Haltroy&lt;/Author&gt;
        ///		&lt;CodeName&gt;com.haltroy.english-gb&lt;/CodeName&gt;
        ///		&lt;CompatibleVersion&gt;1&lt;/CompatibleVersion&gt;
        ///		&lt;Version&gt;1&lt;/Version&gt;
        ///	&lt;/Group&gt;
        ///	&lt;Group Name=&quot;WebSources&quot;&gt;
        ///		&lt;Translation Id=&quot;Reload&quot; Text=&quot;Reload&quot; /&gt;
        ///		&lt;Translation Id=&quot;CertErrorTitle&quot; Text=&quot;Certificate Error&quot; /&gt;
        ///		&lt;Translation Id=&quot;CertErrorDesc&quot; Text=&quot;This website acted malicious so Yorot stopped loading the page [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English_GB {
            get {
                return ResourceManager.GetString("English_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;root&gt;
        ///	&lt;Group Name=&quot;#YOROT-ROOT&quot;&gt;
        ///		&lt;Name&gt;English (United States)&lt;/Name&gt;
        ///		&lt;Author&gt;Haltroy&lt;/Author&gt;
        ///		&lt;CodeName&gt;com.haltroy.english-gb&lt;/CodeName&gt;
        ///		&lt;CompatibleVersion&gt;1&lt;/CompatibleVersion&gt;
        ///		&lt;Version&gt;1&lt;/Version&gt;
        ///	&lt;/Group&gt;
        ///	&lt;Group Name=&quot;WebSources&quot;&gt;
        ///		&lt;Translation Id=&quot;Reload&quot; Text=&quot;Reload&quot; /&gt;
        ///		&lt;Translation Id=&quot;CertErrorTitle&quot; Text=&quot;Certificate Error&quot; /&gt;
        ///		&lt;Translation Id=&quot;CertErrorDesc&quot; Text=&quot;This website acted malicious so Yorot stopped loading the page. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English_US {
            get {
                return ResourceManager.GetString("English_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;[WebSources.ErrorTitle]&lt;/title&gt;
        ///    &lt;style&gt;
        ///        .center {
        ///            margin: auto;
        ///            width: 100%;
        ///            text-align: center;
        ///        }
        ///
        ///        .content {
        ///            max-width: 500px;
        ///            margin: auto;
        ///        }
        ///
        ///        body {
        ///            background-color: [Theme.BackColor];
        ///            color: [Theme.ForeColor];
        ///            font-family: Ubuntu;
        ///            background-size: cover;
        ///            position: relative;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ext_b {
            get {
                object obj = ResourceManager.GetObject("ext_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ext_w {
            get {
                object obj = ResourceManager.GetObject("ext_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap faved_b {
            get {
                object obj = ResourceManager.GetObject("faved_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap faved_w {
            get {
                object obj = ResourceManager.GetObject("faved_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favorite_b {
            get {
                object obj = ResourceManager.GetObject("favorite_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favorite_w {
            get {
                object obj = ResourceManager.GetObject("favorite_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fileman {
            get {
                object obj = ResourceManager.GetObject("fileman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forward_b {
            get {
                object obj = ResourceManager.GetObject("forward_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forward_w {
            get {
                object obj = ResourceManager.GetObject("forward_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap general_settings {
            get {
                object obj = ResourceManager.GetObject("general_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap globe_b {
            get {
                object obj = ResourceManager.GetObject("globe_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap globe_w {
            get {
                object obj = ResourceManager.GetObject("globe_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hamburger {
            get {
                object obj = ResourceManager.GetObject("hamburger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hamburger_w {
            get {
                object obj = ResourceManager.GetObject("hamburger_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home_b {
            get {
                object obj = ResourceManager.GetObject("home_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home_w {
            get {
                object obj = ResourceManager.GetObject("home_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;style&gt;
        ///        .content {
        ///            max-width: 500px;
        ///            margin: auto;
        ///        }
        ///
        ///        body {
        ///            font-family: Ubuntu;
        ///            background-color: rgb(33, 33, 33);
        ///            color: white;
        ///        }
        ///    &lt;/style&gt;
        ///    &lt;title&gt;[WebSources.IncognitoTitle]&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body class=&quot;content&quot;&gt;
        ///    &lt;h1 style=&quot;text-align: center&quot;&gt;&amp;nbsp;&lt;/h1&gt;
        ///    &lt;img style=&quot;display: block; margin-left: auto; margin-right: auto&quot;
        ///         src=&quot;data:image/png;base64,iVBORw0KGgoAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string incognito {
            get {
                return ResourceManager.GetString("incognito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap incognito_b {
            get {
                object obj = ResourceManager.GetObject("incognito_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap incognito_w {
            get {
                object obj = ResourceManager.GetObject("incognito_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kopad {
            get {
                object obj = ResourceManager.GetObject("kopad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;title&gt;§TITLE§&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            background-color: [Theme.BackColor];
        ///            color: [Theme.ForeColor];
        ///            font-family: Ubuntu;
        ///            background-size: cover;
        ///            position: relative;
        ///            background-repeat: no-repeat;
        ///            background-size: 100% 100vh;
        ///        }
        ///
        ///        p {
        ///            font-size: large;
        ///        }
        ///
        ///        .btn-group button {
        ///            background-color: [Theme.OverlayColor];
        ///            borde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;title&gt;Yorot Links&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            background-color: [Theme.BackColor];
        ///            color: [Theme.ForeColor];
        ///            font-family: Ubuntu;
        ///            background-size: cover;
        ///            position: relative;
        ///            background-repeat: no-repeat;
        ///            background-size: 100% 100vh;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;List of Yorot Links&lt;/h1&gt;
        ///    &lt;p&gt;
        ///        • &lt;a href=&quot;yorot://technical&quot;&gt;yorot://technical&lt;/a&gt; - Technical Informat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string links {
            get {
                return ResourceManager.GetString("links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style&gt;
        ///        .yorotMap {
        ///            height: 100%;
        ///            width: 100%;
        ///        }
        ///
        ///        svg {
        ///            -ms-touch-action: none;
        ///            touch-action: none
        ///        }
        ///
        ///        image, text, .jsvmap-zoomin, .jsvmap-zoomout {
        ///            -ms-user-select: none;
        ///            user-select: none
        ///        }
        ///
        ///        .jsvmap-container {
        ///            -ms-touch-action: none;
        ///            touch-action: none;
        ///            position: relative;
        ///            overfl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mute {
            get {
                object obj = ResourceManager.GetObject("mute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mute_w {
            get {
                object obj = ResourceManager.GetObject("mute_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;title&gt;[WebSources.NewTab]&lt;/title&gt;
        ///    &lt;style&gt;
        ///        :root {
        ///            --rad: 0.7rem;
        ///            --dur: 0.3s;
        ///            --color-dark: #2f2f2f;
        ///            --color-light: #fff;
        ///            --color-brand: [Theme.OverlayColor];
        ///            --font-fam: &quot;Lato&quot;, sans-serif;
        ///            --height: 5rem;
        ///            --btn-width: 6rem;
        ///            --bez: cubic-bezier(0, 0, 0.43, 1.49);
        ///        }
        ///
        ///        * {
        ///            box-sizing: border-box;
        ///        }
        ///
        ///        .center {
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string newtab {
            get {
                return ResourceManager.GetString("newtab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;[WebSources.NoIntTitle]&lt;/title&gt;
        ///    &lt;!--
        ///          Hello am 21 year man from tukrey. Sorry for my bed england. I not selled my wife for internet connection
        ///          for nothing. me love me wife. please copy pasterino my story.
        ///          --&gt;
        ///    &lt;style&gt;
        ///        .center {
        ///            margin: auto;
        ///            width: 100%;
        ///            text-align: center;
        ///        }
        ///
        ///        .content {
        ///            max-width: 500px;
        ///            margin: auto;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string noint {
            get {
                return ResourceManager.GetString("noint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notepad {
            get {
                object obj = ResourceManager.GetObject("notepad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pin_b {
            get {
                object obj = ResourceManager.GetObject("pin_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pin_w {
            get {
                object obj = ResourceManager.GetObject("pin_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap profiles {
            get {
                object obj = ResourceManager.GetObject("profiles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_b {
            get {
                object obj = ResourceManager.GetObject("refresh_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_w {
            get {
                object obj = ResourceManager.GetObject("refresh_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap safe_b {
            get {
                object obj = ResourceManager.GetObject("safe_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap safe_w {
            get {
                object obj = ResourceManager.GetObject("safe_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap security_settings {
            get {
                object obj = ResourceManager.GetObject("security_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spacepass {
            get {
                object obj = ResourceManager.GetObject("spacepass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap speaker {
            get {
                object obj = ResourceManager.GetObject("speaker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap speaker_w {
            get {
                object obj = ResourceManager.GetObject("speaker_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop_b {
            get {
                object obj = ResourceManager.GetObject("stop_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop_w {
            get {
                object obj = ResourceManager.GetObject("stop_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap store {
            get {
                object obj = ResourceManager.GetObject("store", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;title&gt;Yorot&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            background-color: [Theme.BackColor];
        ///            color: [Theme.ForeColor];
        ///            font-family: Ubuntu;
        ///            background-size: cover;
        ///            position: relative;
        ///            background-repeat: no-repeat;
        ///            background-size: 100% 100vh;
        ///        }
        ///
        ///        textarea {
        ///            font-family: Ubuntu;
        ///            background-size: cover;
        ///            position: relative;
        ///            background-repeat: no- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string technical {
            get {
                return ResourceManager.GetString("technical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;title&gt;Tests&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Tests&lt;/h1&gt;
        ///    &lt;button onclick=&quot;alert(&quot; I am an alert box!&quot;);&quot;&gt;Alert test&lt;/button&gt;
        ///&lt;/body&gt;.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trash {
            get {
                object obj = ResourceManager.GetObject("trash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trash_w {
            get {
                object obj = ResourceManager.GetObject("trash_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;root&gt;
        ///	&lt;Group Name=&quot;#YOROT-ROOT&quot;&gt;
        ///		&lt;Name&gt;Türkçe&lt;/Name&gt;
        ///		&lt;Author&gt;Haltroy&lt;/Author&gt;
        ///		&lt;CodeName&gt;com.haltroy.turkish&lt;/CodeName&gt;
        ///		&lt;CompatibleVersion&gt;1&lt;/CompatibleVersion&gt;
        ///		&lt;Version&gt;1&lt;/Version&gt;
        ///	&lt;/Group&gt;
        ///	&lt;Group Name=&quot;WebSources&quot;&gt;
        ///		&lt;Translation Id=&quot;Reload&quot; Text=&quot;Yenile&quot; /&gt;
        ///		&lt;Translation Id=&quot;CertErrorTitle&quot; Text=&quot;Sertifika Hatası&quot; /&gt;
        ///		&lt;Translation Id=&quot;CertErrorDesc&quot; Text=&quot;Bu website kötü niyetli davrandı ve bu yüzden Yorot yüklemeyi durdurdu.&quot; /&gt;
        ///		&lt;Tran [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unmute {
            get {
                object obj = ResourceManager.GetObject("unmute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unsafe_b {
            get {
                object obj = ResourceManager.GetObject("unsafe_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unsafe_w {
            get {
                object obj = ResourceManager.GetObject("unsafe_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update_and_about {
            get {
                object obj = ResourceManager.GetObject("update_and_about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Yorot {
            get {
                object obj = ResourceManager.GetObject("Yorot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;title&gt;[WIP] §PAGETITLE§&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;§PAGETITLE§&lt;/h1&gt;
        ///    &lt;a&gt;
        ///        TODO: Embed and add all required legal information as a expandable item list.&lt;a&gt;
        ///            &lt;h2 href=&quot;https://www.flaticon.com/authors/freepik&quot;&gt;§FREEPIK§&lt;/h2&gt;
        ///&lt;/body&gt;.
        /// </summary>
        internal static string yorot_licenses {
            get {
                return ResourceManager.GetString("yorot_licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YorotDark {
            get {
                object obj = ResourceManager.GetObject("YorotDark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YorotDeepBlue {
            get {
                object obj = ResourceManager.GetObject("YorotDeepBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YorotLight {
            get {
                object obj = ResourceManager.GetObject("YorotLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YorotRazor {
            get {
                object obj = ResourceManager.GetObject("YorotRazor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YorotShadow {
            get {
                object obj = ResourceManager.GetObject("YorotShadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YorotStone {
            get {
                object obj = ResourceManager.GetObject("YorotStone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
