//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yorot_Avalonia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yorot_Avalonia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;title&gt;Yorot&lt;/title&gt;
        ///    &lt;style&gt;
        ///        html,
        ///        body {
        ///            height: 100%;
        ///            background: #660000;
        ///            color: white;
        ///            font: Ubuntu;
        ///        }
        ///
        ///        .parent {
        ///            height: 200px;
        ///            background: #660000;
        ///            display: flex;
        ///            align-items: center;
        ///            justify-content: center;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body class=&quot;parent&quot;&gt;
        ///    &lt;div class=&quot;content&quot;&gt;
        ///        &lt;h1 style=&quot;text-align: center&quot;&gt;[W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string certerror {
            get {
                return ResourceManager.GetString("certerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;root&gt;
        ///	&lt;Group Name=&quot;#YOROT-ROOT&quot;&gt;
        ///		&lt;Name&gt;English (United Kingdom)&lt;/Name&gt;
        ///		&lt;Author&gt;Haltroy&lt;/Author&gt;
        ///		&lt;CodeName&gt;com.haltroy.english-gb&lt;/CodeName&gt;
        ///		&lt;CompatibleVersion&gt;1&lt;/CompatibleVersion&gt;
        ///		&lt;Version&gt;1&lt;/Version&gt;
        ///	&lt;/Group&gt;
        ///	&lt;Group Name=&quot;RightClick&quot;&gt;
        ///		&lt;Translation ID=&quot;Back&quot; Text=&quot;Go Back&quot; /&gt;
        ///		&lt;Translation ID=&quot;Forward&quot; Text=&quot;Go Forward&quot; /&gt;
        ///		&lt;Translation ID=&quot;Refresh&quot; Text=&quot;Refresh&quot; /&gt;
        ///		&lt;Translation ID=&quot;RefreshNoCache&quot; Text=&quot;Refresh (No Cache)&quot; /&gt;
        ///		&lt;Tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English_GB {
            get {
                return ResourceManager.GetString("English_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;root&gt;
        ///	&lt;Group Name=&quot;#YOROT-ROOT&quot;&gt;
        ///		&lt;Name&gt;English (United States)&lt;/Name&gt;
        ///		&lt;Author&gt;Haltroy&lt;/Author&gt;
        ///		&lt;CodeName&gt;com.haltroy.english-gb&lt;/CodeName&gt;
        ///		&lt;CompatibleVersion&gt;1&lt;/CompatibleVersion&gt;
        ///		&lt;Version&gt;1&lt;/Version&gt;
        ///	&lt;/Group&gt;
        ///	&lt;Group Name=&quot;RightClick&quot;&gt;
        ///		&lt;Translation ID=&quot;Back&quot; Text=&quot;Go Back&quot; /&gt;
        ///		&lt;Translation ID=&quot;Forward&quot; Text=&quot;Go Forward&quot; /&gt;
        ///		&lt;Translation ID=&quot;Refresh&quot; Text=&quot;Refresh&quot; /&gt;
        ///		&lt;Translation ID=&quot;RefreshNoCache&quot; Text=&quot;Refresh (No Cache)&quot; /&gt;
        ///		&lt;Tra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English_US {
            get {
                return ResourceManager.GetString("English_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;[WebSources.ErrorTitle]&lt;/title&gt;
        ///    &lt;style&gt;
        ///        .center {
        ///            margin: auto;
        ///            width: 100%;
        ///            text-align: center;
        ///        }
        ///
        ///        .content {
        ///            max-width: 500px;
        ///            margin: auto;
        ///        }
        ///
        ///        body {
        ///            background-color: [Theme.BackColor];
        ///            color: [Theme.ForeColor];
        ///            font-family: Ubuntu;
        ///            background-size: cover;
        ///            position: relative;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;style&gt;
        ///        .content {
        ///            max-width: 500px;
        ///            margin: auto;
        ///        }
        ///
        ///        body {
        ///            font-family: Ubuntu;
        ///            background-color: rgb(33, 33, 33);
        ///            color: white;
        ///        }
        ///    &lt;/style&gt;
        ///    &lt;title&gt;[WebSources.IncognitoTitle]&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body class=&quot;content&quot;&gt;
        ///    &lt;h1 style=&quot;text-align: center&quot;&gt;&amp;nbsp;&lt;/h1&gt;
        ///    &lt;img style=&quot;display: block; margin-left: auto; margin-right: auto&quot;
        ///         src=&quot;data:image/png;base64,iVBORw0KGgoAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string incognito {
            get {
                return ResourceManager.GetString("incognito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;title&gt;§TITLE§&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            background-color: [Theme.BackColor];
        ///            color: [Theme.ForeColor];
        ///            font-family: Ubuntu;
        ///            background-size: cover;
        ///            position: relative;
        ///            background-repeat: no-repeat;
        ///            background-size: 100% 100vh;
        ///        }
        ///
        ///        p {
        ///            font-size: large;
        ///        }
        ///
        ///        .btn-group button {
        ///            background-color: [Theme.OverlayColor];
        ///            borde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;title&gt;Yorot Links&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            background-color: [Theme.BackColor];
        ///            color: [Theme.ForeColor];
        ///            font-family: Ubuntu;
        ///            background-size: cover;
        ///            position: relative;
        ///            background-repeat: no-repeat;
        ///            background-size: 100% 100vh;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;List of Yorot Links&lt;/h1&gt;
        ///    &lt;p&gt;• &lt;a href=&quot;yorot://technical&quot;&gt;yorot://technical&lt;/a&gt; - Technical Information&lt;/p&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string links {
            get {
                return ResourceManager.GetString("links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style&gt;
        ///        .yorotMap {
        ///            height: 100%;
        ///            width: 100%;
        ///        }
        ///
        ///        svg {
        ///            -ms-touch-action: none;
        ///            touch-action: none
        ///        }
        ///
        ///        image, text, .jsvmap-zoomin, .jsvmap-zoomout {
        ///            -ms-user-select: none;
        ///            user-select: none
        ///        }
        ///
        ///        .jsvmap-container {
        ///            -ms-touch-action: none;
        ///            touch-action: none;
        ///            position: relative;
        ///            overfl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;title&gt;[WebSources.NewTab]&lt;/title&gt;
        ///    &lt;style&gt;
        ///        :root {
        ///            --rad: 0.7rem;
        ///            --dur: 0.3s;
        ///            --color-dark: #2f2f2f;
        ///            --color-light: #fff;
        ///            --color-brand: [Theme.OverlayColor];
        ///            --font-fam: &quot;Lato&quot;, sans-serif;
        ///            --height: 5rem;
        ///            --btn-width: 6rem;
        ///            --bez: cubic-bezier(0, 0, 0.43, 1.49);
        ///        }
        ///
        ///        * {
        ///            box-sizing: border-box;
        ///        }
        ///
        ///        .center {
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string newtab {
            get {
                return ResourceManager.GetString("newtab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;[WebSources.NoIntTitle]&lt;/title&gt;
        ///    &lt;!--
        ///          Hello am 21 year man from tukrey. Sorry for my bed england. I not selled my wife for internet connection
        ///          for nothing. me love me wife. please copy pasterino my story.
        ///          --&gt;
        ///    &lt;style&gt;
        ///        .center {
        ///            margin: auto;
        ///            width: 100%;
        ///            text-align: center;
        ///        }
        ///
        ///        .content {
        ///            max-width: 500px;
        ///            margin: auto;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string noint {
            get {
                return ResourceManager.GetString("noint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;title&gt;Yorot&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            background-color: [Theme.BackColor];
        ///            color: [Theme.ForeColor];
        ///            font-family: Ubuntu;
        ///            background-size: cover;
        ///            position: relative;
        ///            background-repeat: no-repeat;
        ///            background-size: 100% 100vh;
        ///        }
        ///
        ///        textarea {
        ///            font-family: Ubuntu;
        ///            background-size: cover;
        ///            position: relative;
        ///            background-repeat: no- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string technical {
            get {
                return ResourceManager.GetString("technical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///    &lt;title&gt;Tests&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Tests&lt;/h1&gt;
        ///    &lt;button onclick=&quot;alert(&apos;I am an alert box!&apos;);&quot;&gt;Alert test&lt;/button&gt;
        ///&lt;/body&gt;.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;root&gt;
        ///	&lt;Group Name=&quot;#YOROT-ROOT&quot;&gt;
        ///		&lt;Name&gt;Türkçe&lt;/Name&gt;
        ///		&lt;Author&gt;Haltroy&lt;/Author&gt;
        ///		&lt;CodeName&gt;com.haltroy.turkish&lt;/CodeName&gt;
        ///		&lt;CompatibleVersion&gt;1&lt;/CompatibleVersion&gt;
        ///		&lt;Version&gt;1&lt;/Version&gt;
        ///	&lt;/Group&gt;
        ///
        ///	&lt;Group Name=&quot;RightClick&quot;&gt;
        ///		&lt;Translation ID=&quot;Back&quot; Text=&quot;Geri Git&quot; /&gt;
        ///		&lt;Translation ID=&quot;Forward&quot; Text=&quot;İleri Git&quot; /&gt;
        ///		&lt;Translation ID=&quot;Refresh&quot; Text=&quot;Yenile&quot; /&gt;
        ///		&lt;Translation ID=&quot;RefreshNoCache&quot; Text=&quot;Yenile (Önbelleksiz)&quot; /&gt;
        ///		&lt;Translation ID=&quot;Stop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
    }
}
