version: appveyor-{build}
configuration: Release
platform:
 - x86
 - x64
only_commits:
 message: /AppVeyorBuild/
before_build:
 - cmd: nuget restore
build:
  project: Yorot-Win32/Yorot.csproj
artifacts:
- path: /Yorot-Win32\bin\Release\x64/
  name: AppveyorLatestBuild-Desktop-x64
- path: /Yorot-Win32\bin\Release\x86/
  name: AppveyorLatestBuild-Desktop-x86